version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/sdlserver
hooks:
    AfterInstall:
    - location: deploy/install-pkgs.sh
      runas: root
    ApplicationStop:
    - location: deploy/stop.sh
      runas: root
    ApplicationStart: 
    - location: deploy/start.sh
      runas: root